
service: solution
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
functions:
  graphql:
    handler: src/apollo-server.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
plugins:
  - serverless-webpack
custom:
  webpack:
    includeModules: true